# Step 1: Build Stage, Code Optimization
FROM node:14-alpine AS build-stage

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

# Step 2: Server
FROM nginx:stable-alpine

COPY --from=build-stage /app/build /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]